sudo: required
dist: trusty
language: shell
# Attempt to cache TeX
cache:
  edge: true
  yarn: true
  pip: true
  directories:
   - /tmp/texlive
   - $HOME/.texlive
   - $HOME/save

before_install:
  - sudo apt-get install python-software-properties
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update 
  - sudo apt-get install --allow-unauthenticated -y -qq aria2 xzdec yarn pkg-config wget python3 python3-pip git
  - bash scripts/getPandoc.sh
  - bash scripts/firaFonts.sh
  - cp scripts/texlive.profile $HOME/texlive.profile
  - source ./scripts/TeXLive.sh

install:
  - sudo easy_install -U setuptools
  - sudo pip3 install panflute pandoc-eqnos
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

script:
  - yarn && gulp

deploy:
  - provider: surge
    skip_cleanup: true
    project: ./dist/
    domain: $SURGE_DOMAIN
  - provider: pages
    local_dir: ./dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
